services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: polling_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_admin
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  poll-service:
    build:
      context: ./poll-service
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    depends_on:
      - postgres
volumes:
  postgres_data: